<?php
// ----------------------------------------------------------------------
// THIS FILE IS GENERATED BY BACKEND-API. PLEASE! DO NOT MODIFY ANYTHING!
// ----------------------------------------------------------------------
$data = <<< EOT
[{"id":1,"habitat":1,"name_eng":"tank 1","name_arabic":"tank 1 arabic","direction_label_eng":"exit","direction_label_arabic":"exit","direction":0,"quiz_item":["1: Quzi 1","2: Quiz 2"]},{"id":2,"habitat":2,"name_eng":"Asian Planted","name_arabic":"الحوض الآسيوى المزروع","direction_label_eng":"direction label en","direction_label_arabic":"direction label ar","direction":3,"quiz_item":["3: 6-1-1","4: 6-1-2","5: 6-1-3","6: 6-1-4","7: 6-1-5","8: 6-1-7","9: 6-1-6","10: 6-1-8","11: 6-2-1","12: 6-4-1","13: 6-3-1","14: 6-3-2","15: 6-3-3","16: 6-3-4","17: 6-3-5","18: 6-3-6"]}]
EOT;


function parse($text) {
    // Damn pesky carriage returns...
    $text = str_replace("\r\n", "\n", $text);
    $text = str_replace("\r", "\n", $text);

    // JSON requires new line characters be escaped
    $text = str_replace("\n", "\\n", $text);
    return $text;
}



header('Content-Type: application/json');
echo parse($data);
exit;
