# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20160315_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to=quiz.models.upload_to)),
            ],
            options={
                'verbose_name': 'Quiz Image',
                'verbose_name_plural': 'Quiz Images',
            },
        ),
        migrations.RemoveField(
            model_name='quizitem',
            name='image',
        ),
        migrations.AddField(
            model_name='quizimage',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizItem'),
        ),
    ]
