# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20160315_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_eng', models.TextField()),
                ('text_arabic', models.TextField()),
            ],
            options={
                'verbose_name': 'Quiz Text',
                'verbose_name_plural': 'Quiz Texts',
            },
        ),
        migrations.RemoveField(
            model_name='quizitem',
            name='text_arabic',
        ),
        migrations.RemoveField(
            model_name='quizitem',
            name='text_eng',
        ),
        migrations.AddField(
            model_name='quiztext',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizItem'),
        ),
    ]
