# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20160315_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizitem',
            name='item_type',
        ),
    ]
