# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_quizitem_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizimage',
            old_name='quiz_id',
            new_name='quiz_item',
        ),
        migrations.RenameField(
            model_name='quiztext',
            old_name='quiz_id',
            new_name='quiz_item',
        ),
    ]
