# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20160316_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='aquarium.Tank'),
        ),
        migrations.AlterField(
            model_name='quizimage',
            name='quiz_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_image', to='quiz.QuizItem'),
        ),
        migrations.AlterField(
            model_name='quizitem',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_item', to='quiz.Grade'),
        ),
        migrations.AlterField(
            model_name='quiztext',
            name='quiz_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_text', to='quiz.QuizItem'),
        ),
    ]
