# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20160316_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='tank',
            new_name='tank_name',
        ),
    ]
