# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20160316_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='quizitems',
        ),
        migrations.AddField(
            model_name='grade',
            name='quizitems',
            field=models.ManyToManyField(to='quiz.QuizItem'),
        ),
    ]
