# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20160316_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizitem',
            old_name='grade_name',
            new_name='grade',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='quizitems',
        ),
    ]
