# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20160316_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterField(
            model_name='quizitem',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
