# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20160316_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizitem',
            name='type',
            field=models.CharField(choices=[(0, 'text'), (1, 'image')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
