# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20160316_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizitem',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image')], max_length=5),
        ),
    ]
