# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20160316_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizimage',
            name='image_arabic',
            field=models.ImageField(default=1, upload_to=quiz.models.upload_to),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizimage',
            name='image',
            field=models.ImageField(upload_to=quiz.models.upload_to),
        ),
    ]
