# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20160316_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizImageTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_eng', models.ImageField(blank=True, null=True, upload_to=quiz.models.upload_to)),
                ('image_arabic', models.ImageField(blank=True, null=True, upload_to=quiz.models.upload_to)),
                ('quiz_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_image_arabic', to='quiz.QuizItem')),
            ],
            options={
                'ordering': ['quiz_item'],
                'verbose_name': 'Quiz Image Table',
                'verbose_name_plural': 'Quiz Image Table',
            },
        ),
        migrations.AlterUniqueTogether(
            name='quizimagearabic',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='quizimagearabic',
            name='quiz_item',
        ),
        migrations.DeleteModel(
            name='QuizImageArabic',
        ),
        migrations.AlterUniqueTogether(
            name='quizimagetable',
            unique_together=set([('quiz_item',)]),
        ),
    ]
