# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20160316_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizitem',
            name='img_table',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
