# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_quizitem_img_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quiztext',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='quiztext',
            name='quiz_item',
        ),
        migrations.AddField(
            model_name='quizitem',
            name='text_arabic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizitem',
            name='text_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizimagetable',
            name='quiz_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_image_table', to='quiz.QuizItem'),
        ),
        migrations.DeleteModel(
            name='QuizText',
        ),
    ]
