# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0008_remove_tank_grades'),
        ('quiz', '0027_auto_20160316_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='tank',
        ),
        migrations.AddField(
            model_name='quizitem',
            name='tank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='aquarium.Tank'),
            preserve_default=False,
        ),
    ]
