# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20160316_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizitem',
            name='image_arabic',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.upload_to),
        ),
        migrations.AddField(
            model_name='quizitem',
            name='image_eng',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.upload_to),
        ),
    ]
