# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20160317_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizitem',
            old_name='image_arabic',
            new_name='image_table_arabic',
        ),
        migrations.RenameField(
            model_name='quizitem',
            old_name='image_eng',
            new_name='image_table_eng',
        ),
    ]
