# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_auto_20160317_0925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizItem',
            new_name='Quiz',
        ),
        migrations.AlterUniqueTogether(
            name='quizimagetable',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='quizimagetable',
            name='quiz_item',
        ),
        migrations.DeleteModel(
            name='QuizImageTable',
        ),
    ]
