# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_auto_20160317_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image'), ('image table', 'image table')], max_length=11),
        ),
    ]
