# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_auto_20160317_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image'), ('image_table', 'image_table')], max_length=11),
        ),
    ]
