# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0008_remove_tank_grades'),
        ('quiz', '0034_auto_20160317_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='tank',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='img_table',
        ),
        migrations.AddField(
            model_name='quiz',
            name='position',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='tank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aquarium.Tank'),
            preserve_default=False,
        ),
    ]
