# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_auto_20160317_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='position',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]),
        ),
    ]
