# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_auto_20160317_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='tank',
        ),
    ]
