# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizimage',
            unique_together=set([('quiz_item', 'image')]),
        ),
    ]
