# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:35
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0042_auto_20160319_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='text_arabic',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='text_eng',
            field=tinymce.models.HTMLField(),
        ),
    ]
