# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0018_auto_20160319_2114'),
        ('quiz', '0044_remove_quiz_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='tank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aquarium.Tank'),
            preserve_default=False,
        ),
    ]
