# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0019_auto_20160319_2128'),
        ('quiz', '0045_quiz_tank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='tank',
        ),
        migrations.AddField(
            model_name='quiz',
            name='tank_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='tank', to='aquarium.Tank'),
            preserve_default=False,
        ),
    ]
