# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0046_auto_20160319_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='tank_name',
            new_name='tank',
        ),
    ]
