# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import quiz.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0047_auto_20160320_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AlterModelOptions(
            name='quizimage',
            options={'verbose_name': 'Quiz Image', 'verbose_name_plural': 'Quiz Images'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='images',
            field=models.ManyToManyField(to='quiz.QuizImage'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='text_arabic',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='text_eng',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.upload_to),
        ),
        migrations.AlterUniqueTogether(
            name='quizimage',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='quizimage',
            name='quiz_item',
        ),
    ]
