# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0049_auto_20160320_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
