# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0050_auto_20160320_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
