# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0051_auto_20160320_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='position',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)]),
        ),
    ]
