# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0054_auto_20160320_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['id'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='images',
            field=models.ManyToManyField(blank=True, to='quiz.Image'),
        ),
    ]
