# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0055_auto_20160320_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
            options={
                'verbose_name': 'Image Test',
                'verbose_name_plural': 'Image Test',
            },
        ),
    ]
