# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0056_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.upload_to_test),
        ),
    ]
