# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0058_auto_20160320_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='text_arabic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='text_eng',
            field=models.TextField(blank=True, null=True),
        ),
    ]
