# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0060_auto_20160325_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Testing', 'verbose_name_plural': 'Testing'},
        ),
    ]
