<?php
// ----------------------------------------------------------------------
// THIS FILE IS GENERATED BY BACKEND-API. PLEASE! DO NOT MODIFY ANYTHING!
// ----------------------------------------------------------------------
$data = <<< EOT
[]
EOT;


function parse($text) {
    // Damn pesky carriage returns...
    $text = str_replace("\r\n", "\n", $text);
    $text = str_replace("\r", "\n", $text);

    // JSON requires new line characters be escaped
    $text = str_replace("\n", "\\n", $text);
    return $text;
}



header('Content-Type: application/json');
echo parse($data);
exit;
