<?php
// ----------------------------------------------------------------------
// THIS FILE IS GENERATED BY BACKEND-API. PLEASE! DO NOT MODIFY ANYTHING!
// ----------------------------------------------------------------------
$data = <<< EOT
[{"id":1,"text_eng":"<p>text eng</p>","text_arabic":"<p>text arabic</p>"},{"id":2,"text_eng":"<p>Text eng 2</p>","text_arabic":"<p>text arabic 2</p>"},{"id":3,"text_eng":"Nearly 90 percent of the 1.2 billion people living in extreme poverty worldwide depend on forest for their livelihoods.","text_arabic":"العالم و90% منهم يعتمدون على الغابات للحصول على الرزق."},{"id":4,"text_eng":"Fifty-seven percent of the world’s forest, including most tropical forest, are located in developing countries.","text_arabic":"تقع سبعة وخمسون بالمائة من الغابات فى العالم بما فى ذلك الغابات"}]
EOT;


function parse($text) {
    // Damn pesky carriage returns...
    $text = str_replace("\r\n", "\n", $text);
    $text = str_replace("\r", "\n", $text);

    // JSON requires new line characters be escaped
    $text = str_replace("\n", "\\n", $text);
    return $text;
}



header('Content-Type: application/json');
echo parse($data);
exit;
