# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0002_map_is_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='map',
            new_name='image',
        ),
    ]
