# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20160316_1211'),
        ('aquarium', '0003_auto_20160315_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='grades',
            field=models.ManyToManyField(to='quiz.Grade'),
        ),
    ]
