# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20160316_1211'),
        ('aquarium', '0004_tank_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='grades',
        ),
        migrations.AddField(
            model_name='tank',
            name='grades',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Grade'),
            preserve_default=False,
        ),
    ]
