# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0007_tank_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='grades',
        ),
    ]
