# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0009_trivia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='habitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia', to='aquarium.Habitat'),
        ),
    ]
