# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0010_auto_20160318_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trivia',
            options={'verbose_name': 'Trivia', 'verbose_name_plural': 'Trivia'},
        ),
    ]
