# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_auto_20160317_1409'),
        ('aquarium', '0011_auto_20160318_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='quizintank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Grade'),
            preserve_default=False,
        ),
    ]
