# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0012_tank_quizintank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='quizintank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
    ]
