# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0039_remove_quiz_tank'),
        ('aquarium', '0013_auto_20160319_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='grade',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='quiz.Grade'),
            preserve_default=False,
        ),
    ]
