# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0014_tank_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='quizintank',
        ),
    ]
