# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0018_auto_20160319_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='tank_quiz',
            field=models.ManyToManyField(to='quiz.Quiz'),
        ),
    ]
