# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0019_auto_20160319_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='tank_quiz',
        ),
    ]
