# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0020_remove_tank_tank_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia',
            name='habitat',
        ),
        migrations.RemoveField(
            model_name='trivia',
            name='text_arabic',
        ),
        migrations.RemoveField(
            model_name='trivia',
            name='text_eng',
        ),
        migrations.AddField(
            model_name='habitat',
            name='trivia',
            field=models.ManyToManyField(related_name='trivia_item', to='aquarium.Trivia'),
        ),
        migrations.AddField(
            model_name='trivia',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic')], default='english', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trivia',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
