# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0021_auto_20160320_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trivia',
            old_name='text',
            new_name='text_arabic',
        ),
        migrations.RemoveField(
            model_name='trivia',
            name='language',
        ),
        migrations.AddField(
            model_name='trivia',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trivia',
            name='text_eng',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
