# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0022_auto_20160320_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitat',
            name='trivia',
            field=models.ManyToManyField(to='aquarium.Trivia'),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
