# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0026_auto_20160321_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='tank_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
