# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0029_auto_20160325_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tank',
            old_name='tank_id',
            new_name='tank_id',
        ),
        migrations.AlterField(
            model_name='species',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquarium.Tank', to_field='tank_id'),
        ),
    ]
