<?php
// ----------------------------------------------------------------------
// THIS FILE IS GENERATED BY BACKEND-API. PLEASE! DO NOT MODIFY ANYTHING!
// ----------------------------------------------------------------------
$data = <<< EOT
[{"id":3,"image":"quiz/article-2559490-1B7DF52A00000578-128_634x452.jpg"},{"id":2,"image":"quiz/RTV.png"},{"id":1,"image":"quiz/treasue-map.jpg"},{"id":4,"image":"quiz/RTV_TipCXNQ.png"},{"id":5,"image":"quiz/article-2559490-1B7DF52A00000578-128_634x452_JzkdYpY.jpg"},{"id":6,"image":"quiz/RTV_ArYJkCY.png"},{"id":7,"image":"quiz/Tricolor-sharkminnow.png"},{"id":8,"image":"quiz/Molly.png"},{"id":9,"image":"quiz/Clown-Loach.png"},{"id":10,"image":"quiz/Tiger-barb.png"},{"id":11,"image":"quiz/Assorted-Rainbowfish.png"},{"id":12,"image":"quiz/Assorted-Rainbowfish_isAHfOn.png"}]
EOT;


function parse($text) {
    // Damn pesky carriage returns...
    $text = str_replace("\r\n", "\n", $text);
    $text = str_replace("\r", "\n", $text);

    // JSON requires new line characters be escaped
    $text = str_replace("\n", "\\n", $text);
    return $text;
}



header('Content-Type: application/json');
echo parse($data);
exit;
